FROM tomcat:8.5

MAINTAINER "auction-1"

EXPOSE 8080

RUN	 rm -rf /usr/local/tomcat/webapps/Auction-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT /usr/local/tomcat/webapps/Auction-0.0.1-SNAPSHOT

COPY ./target/Auction-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

CMD ["catalina.sh","run"]
